tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'telemachus/anytap'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'ansible'
brew 'awscli'
brew 'binutils'
brew 'chruby'
brew 'cowsay'
brew 'ctags'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'elixir'
brew 'erlang'
brew 'figlet'
brew 'fortune'
brew 'gist'
brew 'git'
brew 'gnu-tar'
brew 'gnu-units'
brew 'gnutls'
brew 'go'
brew 'grc'
brew 'heroku-toolbelt'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'leiningen'
brew 'lnav'
brew 'lua'
brew 'macvim', args: ['override-system-vim']
brew 'msmtp'
brew 'mutt', args: ['with-trash-patch', 'with-sidebar-patch', 'with-confirm-attachment-patch']
brew 'mysql'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'offline-imap'
brew 'openssl'
brew 'ossp-uuid'
brew 'pandoc'
brew 'phantomjs'
brew 'postgresql'
brew 'reattach-to-user-namespace'
brew 'ruby-install'
brew 'sqlite'
brew 'tarsnap'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'urlview'
brew 'w3m'
brew 'wget'
brew 'zsh'

brew 'rcm'

cask 'alfred'
cask 'cloud'
cask 'consul'
# cask 'dropbox'
# cask 'evernote'
cask 'flux'
# cask 'google-chrome'
cask 'iterm2'
cask 'keybase'
cask 'mactex'
# cask '1password'
cask 'packer'
cask 'skitch'
cask 'spotify'
cask 'steam'
cask 'terraform'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'xquartz'
