#!/bin/bash

brew bundle --global

. $(brew --prefix asdf)/libexec/asdf.sh

for plugin in $(cat ../.asdf-plugins); do
    asdf plugin-list | grep $plugin > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        asdf plugin-add $plugin
    fi
done

pushd ~/
asdf install
popd

ln -sf ~/.dotfiles/spaceship-prompt/spaceship.zsh $(brew --prefix)/share/zsh/site-functions/prompt_spaceship_setup
