#!/bin/bash

brew bundle --global
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

. /usr/local/opt/asdf/asdf.sh

for plugin in $(cat ../.asdf-plugins); do
    asdf plugin-list | grep $plugin > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        asdf plugin-add $plugin
    fi
done

pushd ~/
GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" asdf install
popd
